## Numpy 

In [11]:
print('Hello Numpy')

Hello Numpy


### การสร้างอาร์เรย์ 1 มิติ

```bash
  print(nums): คำสั่งนี้จะแสดงค่าในอาร์เรย์ nums ซึ่งในกรณีนี้คือ [1 2 3 4 5].
  print(type(nums)): คำสั่งนี้จะแสดงชนิดประเภทของ nums ซึ่งเป็น <class 'numpy.ndarray'>.
  print(nums.shape): คำสั่งนี้จะแสดงรูปร่าง (shape) ของอาร์เรย์ nums. ในกรณีนี้คือ (5,) ซึ่งหมายถึงอาร์เรย์นี้มี 5 อิลิเมนต์ในแนวเดียวกัน (1 มิติ).
  print(nums.ndim): คำสั่งนี้จะแสดงจำนวนมิติ (dimensions) ของอาร์เรย์ nums. ในกรณีนี้คือ 1 หมายถึงเป็นอาร์เรย์ 1 มิติ.
  print(nums.dtype): คำสั่งนี้จะแสดงชนิดข้อมูล (data type) ของอาร์เรย์ nums. ในกรณีนี้คือ int64 หรือ int32 ขึ้นอยู่กับแพลตฟอร์มที่คุณใช้.
```


In [12]:
import numpy as np # type: ignore

nums = np.array([1,2,3,4,5])

print(nums) #[1 2 3 4 5]
print(type(nums)) #<class 'numpy.ndarray'>
print(nums.shape)
print(nums.ndim) 
print(nums.dtype) 

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1
int64


### การสร้างอาร์เรย์ 2 มิติ

```python
  _2d = 2 มิติ
```


In [13]:
import numpy as np # type: ignore

nums_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(nums_2d)
print(type(nums_2d))
print(nums_2d.shape)
print(nums_2d.ndim)
print(nums_2d.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2
int64


### การสร้างอาร์เรย์ 3 มิติ
```python
  _3d = 3 มิติ
```


In [14]:
import numpy as np # type: ignore

nums_3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                    [[7, 8, 9], [10, 11, 12]]])
print(nums_3d)
print(type(nums_3d))
print(nums_3d.shape)
print(nums_3d.ndim)
print(nums_3d.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
(2, 2, 3)
3
int64


### การสร้างอาร์เรย์ 4 มิติ
```python
  _4d = 4 มิติ
```


In [15]:
import numpy as np # type: ignore

nums_4d = np.array([[[[1, 2, 3], [4, 5, 6]], 
                      [[7, 8, 9], [10, 11, 12]]], 
                    [[[13, 14, 15], [16, 17, 18]], 
                      [[19, 20, 21], [22, 23, 24]]]])
print(nums_4d)
print(type(nums_4d))
print(nums_4d.shape)
print(nums_4d.ndim)
print(nums_4d.dtype)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]]
<class 'numpy.ndarray'>
(2, 2, 2, 3)
4
int64
